### ISSUE TITLE
Server-side render with Flux instances

### ISSUE THREAD

**Issue by voronianski** [goatslacker/alt#18]
One more question for you. 

I'm trying to server-render my Alt-based Flux application, that's very rough example of what I'm doing on server request:

```javascript
var React = require('react');
var Router = require('react-router');
var routes = require('./src/routes.jsx');
var webAPIUtils = require('./src/webAPIUtils');

app.use('/', function (req, res, next) {
        var flux = require('./src/flux');
        webAPIUtils.getFeeds(function (err, feeds) {
            if (err) {
                return next(err);
            }

            flux.getActions('articles').receiveFeeds(feeds); // sync action
            Router.run(routes, req.url, function (Handler) {
                var content = React.renderToString(React.createElement(Handler, {flux: flux}));
                res.render('base', {
                    title: title,
                    content: content,
                    mainJs: mainJs,
                    mainCss: mainCss
                });
            });
        });
});
```

That's client:

```javascript
import 'babelify/polyfill';

import 'es5-shim';
import 'es5-shim/es5-sham';

import React from 'react';

import router from './router';
import flux from './flux';

window.React = React;

React.initializeTouchEvents(true);

router.run((Handler, state) => {
    flux.getActions('router').routeChange(state);
    React.render(
        React.createElement(Handler, { flux }),
        document.getElementById('android-hybrid-app')
    );
});
```

and how **flux.js** looks like:

```javascript
import Alt from 'alt';

import RouterActions from './shared/actions/RouterActions';
import ArticleActions from './pages/articles/ArticleActions';
import ArticleStore from './pages/articles/ArticleStore';

class Flux extends Alt {
    constructor() {
        super();

        // register flux actions and stores
        this.addActions('router', RouterActions);
        this.addActions('articles', ArticleActions);
        this.addStore('articles', ArticleStore);
    }
}

export default new Flux();
```

But unfortunately ArticleStore on client doesn't contain the result of action which was fired on server.

**Comment by voronianski** [comment]
@goatslacker I've solved that with `takeSnapshot()` on server and `bootstrap()` on client, however maybe you know a nicer way of doing this.

**Comment by goatslacker** [comment]
Did you get this figured out in a reasonable manner?

I'll be loading in your code later on and seeing what's happening. The data should be loaded in without having to bootstrap although if you have any setup/teardown stuff you need to do then it'll take an extra step.

**Comment by ryansukale** [comment]
There is something about this that I am not understanding.

In the flux.js file above, we export `1 instance` of flux.
In the router handler for '/` we simply require that file, which returns us that instance.

Now lets say 100 concurrent requests arrive on '/'. When each of them do a 'require('./src/flux');' would all of them not get back exact same flux instance because the require call was already executed once and the result of module execution is cached? And if all of them return the same flux instance, when we populate the store data, it sounds like they will concurrently step over each other's data.

What am I missing here that makes this work?

**Comment by taion** [comment]
1. The example above is a bit mislabelled - usually "instances" refers to initializing one instance of the application per request, and passing it around w/e.g. React context. In such a case there are (hopefully) trivially no issues with colliding requests.
2. You can do isomorphism with singletons - the basic requirement is that you gather together all of your async actions, bootstrap your stores, dispatch those actions, then flush the stores.

Option 1 leaves you stuck dealing with React context and is a bit harder to work with since you always need the local app instance. Option 2 avoids those issues, but manually collecting futures is a bit of a pain. However, tools like https://github.com/goatslacker/alt/pull/284 and https://github.com/goatslacker/alt/pull/364 will manage away most of the complexity there, while if you're using instances, you're sort of just stuck with them.
