### ISSUE TITLE
Instantiate dispatcher per flux instance to avoid shared Dispatcher singleton

### ISSUE THREAD

**Issue by neilcarpenter** [goatslacker/alt#188]
I'm building an isomorphic app, and decided to use alt instances rather than singleton approach, in order to allow async data bootstrapping on server, and avoid all shared state server side.

This is _working_ fine, but have noticed that as the FB Dispatcher that alt is using is a singleton, there's actually some shared internal reference here - `_lastID` is being incremented whenever a new `dispatchToken` is created ([see here](https://github.com/goatslacker/alt/blob/c91bb1e9aa9cc2521f9d87332c7b2267a2510d98/dist/alt.js#L413)), so every request coming in to the server is using, and incrementing, this same internal variable.

The only immediate issue I can see with this is if I receive a massive amount of traffic (and don't restart the server for a while), and reach the [magic JS integer limit](http://stackoverflow.com/a/307200) then will be left with a verrrrry annoying-to-debug issue...

I appreciate the likelihood of this actually happening is very, very slim, but there's probably other issues with using a singleton dispatcher that I'm not anticipating here.

Looking at [Yahoo's dispatchr](https://github.com/yahoo/dispatchr#differences-from-facebooks-flux-dispatcher) they seem to be instantiating dispatchers on per-instance basis, perhaps something that could be added to alt?

cc/ @josh-a-e

**Comment by goatslacker** [comment]
Wow good find. 

So I've got a bit of bad news, the FB dispatcher is already a class and we already instantiate a new Dispatcher whenever you create a new instance of alt. [See here](https://github.com/goatslacker/alt/blob/master/src/alt/index.js#L40).

The problem is that the `_lastId` reference you pointed at lives outside of the class whereas this should be an internal thing to the dispatcher.

There are three solutions I can think of off the top of my head:

* Patch the [Facebook dispatcher](https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L18) all libraries that depend on it win.
* Replace the dispatcher with our own forked version.
* Create and ship a custom Dispatcher that people can optionally enable [via the config](https://github.com/goatslacker/alt/blob/master/src/alt/index.js#L40).

**Comment by neilcarpenter** [comment]
Ah indeed, I didn't dig that far :)

This seems a pretty basic issue / thing to fix so from that POV it makes sense the patch the original Dispatcher and share the love. But... do you have any experience contributing to FB repos? I see there's a [bit of a process](https://github.com/facebook/flux/blob/master/CONTRIBUTING.md) to do this...

I guess your 2nd and 3rd suggestions both have the advantage of not having to wait on FB repo maintainers... although this bug doesn't seem to be super important, so maybe waiting for PR to be accepted isn't an issue.

Creating a separate dispatcher (via fork or custom Dispatcher) I guess would only be worthwhile if there was going to be any other modifications / enhancements on top of the FB one?

So for me it's a case of "can we wait for FB", (assuming they're happy with PR), versus "add value via custom Dispatcher".

What do you think?

**Comment by goatslacker** [comment]
Probably 1 and 3?

**Comment by neilcarpenter** [comment]
Ohh the FB Dispatcher is only like ~250 LoC! Presumed there was more to it...

Anyway, [PR submitted](https://github.com/facebook/flux/pull/194) :)

The more I think about it, this really is a non-issue, so probably no point creating a custom dispatcher unless there's any other value in this.
