### ISSUE TITLE
Unbind/Rebind actions to stores?

### ISSUE THREAD

**Issue by ryanfields** [goatslacker/alt#320]
Is there a way to unbind or rebind one or more actions to a store?  I have a use case where I need for a store to stop listening to a given action and start listening to a different action.

**Comment by goatslacker** [comment]
Interesting, can you elaborate?

**Comment by ryanfields** [comment]
Webpack has a feature called hot module replacement that allows code changes to be sent to the client wihout performing page reloads.  I'm working on a game project in which it's expensive to reload the whole game to experiment with small changes.

When Webpack hot pushes a store, I can serialize it, detach its listeners, then do the reverse for the incoming code.  Views are even easier.  But when action changes are pushed, I have no way of unbinding the outgoing code before binding the hot push.

**Comment by goatslacker** [comment]
I think this solves your problem:

https://github.com/goatslacker/alt/blob/master/src/utils/makeHot.js

**Comment by goatslacker** [comment]
And the API: https://github.com/goatslacker/alt/issues/85#issuecomment-109793367

**Comment by ryanfields** [comment]
That would work, yes.  It's what I tried to do on my own with my initial attempt.  I was stopped by the fact that the API docs don't mention an official way to delete a store.

Reloading stores when actions change should be left up to the developer, since the module.hot.accept calls are specific to whatever arbitrary action modules have been required.  I think makeHot gives me everything I need, since I the solution I put together was working with the exception of warnings/errors of duplicate stores.

Thanks for pointing this util out.

**Comment by rulatir** [comment]
I need to be able to make a store stop listening to an action. I need this ability directly, as a goal, not as a means to an end that can possibly be reached otherwise. Basically I need a transient store that only exists for some time and not forever (and will be recreated when needed), so I obviously need to be able to detach it from everything it is attached to.

Rationale: dialogs. A dialog **is**, and then it **isn't**. The information specifying that a particular dialog **should no longer be** must be kept in a store (a "closed" flag), but once the parent reflects that state by no longer rendering the dialog, the dialog no longer **is**. Since that piece of information in the store is no longer relevant to anything that **is**, said information itself **should no longer be**. Furthermore, since the store in which said information resides doesn't contain any other information (because it is **the** dedicated dialog state store; any other way would be a failure at distinguishing the machinery from the material it processes), said store becomes empty and useless once the dialog no longer **is**. Therefore the store should also **no longer be**. However this cannot be accomplished without properly disconnecting it from everything that **still is**, and actions **still are**!
