### ISSUE TITLE
@connectToStores SyntaxError

### ISSUE THREAD

**Issue by nlhkh** [goatslacker/alt#381]
I am not sure if `@` is a new valid keyword, but babel does not like it and my code does not build.
I copy this from your README page.

**Comment by jdlehman** [comment]
The `@` symbol notates that a function is being used as a decorator. You need to set up your [`.babelrc`](http://babeljs.io/docs/usage/babelrc/) file so that the `stage` is at a level that supports decorators as they are not official in ES6.  Here is a [list](https://babeljs.io/docs/usage/experimental/) of the experimental features and what stage they are in.  For decorator support you need to be stage 1 or lower (each stage includes all things in higher stages and babel uses stage 2 by default).

A decorator is just a function that wraps a class or function.  So you could just do:

`connectToStores(component);`

Here is an [example](https://github.com/goatslacker/alt/blob/ca7f455e89ea0f9a3b3c7e15f21bc7c10b870aca/src/utils/connectToStores.js#L29-L40)

**Comment by nlhkh** [comment]
Got it, thanks!
