### ISSUE TITLE
Alt & Inline styles (Radium)

### ISSUE THREAD

**Issue by boyswan** [goatslacker/alt#395]
I'm having a problem using the connectToStore decorator alongside Radium, specifically when having multiple styles within an array in a style attribute.

```javascript
import connectToStores from 'alt/utils/connectToStores';
import Radium from 'radium'
import React from 'react'
...

@Radium
@connectToStores
export default class Test extends React.Component {

  static getStores(){
    return [Store];
  }

  static getPropsFromStores(){
    return Store.getState();
  }

	render(){

		return (
			<div style={[Styles.container, Styles.example]}> Dummy </div>
		);

	}

}


let Styles = {

	container: {
	  width: '100%',
		padding:40
	},

	example : {
	  backgroundColor: 'rgba(0,0,0,0.2)'
	}

}
```

No styles are applied when in an array, and using object.assign is causing me other problems. Is this a bug or expected behaviour?

**Comment by jdlehman** [comment]
So the answer to your question is to just swap the order of your decorators.

```js
@connectToStores
@Radium
export default class Test extends React.Component {
```

The reason this works (and I just tested your example locally to confirm) is that `connectToStores` actually wraps your component in a container component. So the `Radium` decorator was being applied to the container rather than your actual `Test` component.

I will update the docs to better reflect this.

**Comment by jdlehman** [comment]
Also, to anyone else reading this in the future, `connectToStores` should typically be your outermost decorator, as decorators are just functions wrapping the class `connectToStores(Radium(YourComponent))`
