### ISSUE TITLE
connectToStores does not work with inheritance

### ISSUE THREAD

**Issue by clouddra** [goatslacker/alt#431]
I am having problems using inheritance with connectToStores.
I think connectToStores uses composition which is not compatible with inheritance.

E.g. The following snippet does not work
```
// parent class
@connectToStores
BaseComponent extends React.Component{
	constructor(props){
		console.log('base');
	}
	...
}

// child class
DerivedComponent extends React.Component{
	constructor(props){
		super(props);
		console.log('derived');
	}
	...
}
```

**Comment by jdlehman** [comment]
The problem is that `@connectToStores` is a function that creates a wrapper component around your component.  This means your `DerivedComponent` is extending the wrapper that `connectToStores` creates rather than your `BaseComponent`.

You would need to define the `BaseComponent` without the decorator, and then extend that with your `DerivedComponent`.  This will get the inheritance working correctly.  After this you can export each of these components with the `connectToStores` decorator.

Essentially more steps and hoops to jump through, but you should be able to get this to work.

**Comment by clouddra** [comment]
@jdlehman Thanks for the explanation. That was what i suspected as well and I have managed to got it work.
