### ISSUE TITLE
Question: Can bindListeners map the same action?

### ISSUE THREAD

**Issue by jcalfee** [goatslacker/alt#456]
Is this correct?  I'm trying to map `ImportKeysActions.saved` to two functions.  The following works as it appears with the second reference commented (`onRefreshBalanceClaims` is called).  However when I uncomment the second action the only method that gets called is `onLoadMyAccounts` ...  I would like to call both methods (in any order) once keys are saved.

```javascript
class BalanceClaimStore {

    constructor() {
        this.bindActions(BalanceClaimActions)
        this.bindListeners({
            onRefreshBalanceClaims: ImportKeysActions.saved,
            onLoadMyAccounts: [
                WalletUnlockActions.change//, ImportKeysActions.saved
            ]
        })
}
```

**Comment by goatslacker** [comment]
That should work, if it doesn't then it sounds like a bug

**Comment by mattkahl** [comment]
I ran into this yesterday, I believe it is not possible because the `actionListeners` dictionary on a store is keyed on an action's `id` and only has a single handler value. 

I was wondering if it was intentional for some reason, but I guess it's not (which is a welcomed insight). 

See `bindAction`: https://github.com/goatslacker/alt/blob/master/src/alt/store/StoreMixin.js

**Comment by goatslacker** [comment]
yeah, we can make that an array though :)

**Comment by mattkahl** [comment]
Ha. Should've said "not working" instead of "not possible". 

I was happy hear you say it's not intended because I couldn't dream up a reason that it would be.

**Comment by goatslacker** [comment]
a57d062f994dd99afc980d3be5dcd5af99678c5d
