### ISSUE TITLE
Can't view Immutable util docs

### ISSUE THREAD

**Issue by jfsiii** [goatslacker/alt#470]
## Steps to reproduce
Enter http://alt.js.org/docs/utils/immutable in browser

## Expected
Expected [docs on immutable utils][imm_utils] be displayed as HTML.

## Observed
File is downloaded to user's computer.

## Notes
This appears to be because of an incorrect [`Content-Type` header value of `application/octet-stream`][failure_header]. Compare with this [successful request for http://alt.js.org/guide/async/][success_header].

[success_header]: https://gist.github.com/jfsiii/6d373dd6af9ecb2c4690#file-curl_async_docs-log-L4
[failure_header]: https://gist.github.com/jfsiii/28550894480be16cca70#file-curl_immutable_docs-log-L4
[imm_utils]: https://github.com/goatslacker/alt/blob/master/docs/utils/immutable.md

**Comment by goatslacker** [comment]
Hmm not sure why :-\

**Comment by mull** [comment]
@goatslacker https://github.com/goatslacker/alt/blob/gh-pages/docs/utils/immutable is missing the .html extension

**Comment by goatslacker** [comment]
Actually it's supposed to be in a folder immutable with an index.html :(

**Comment by jdlehman** [comment]
Hmm, this fix works locally and now correctly generates the `immutable` folder with an `index.html` file.

The problem is that it still does not work for http://alt.js.org/docs/utils/immutable, though http://alt.js.org/docs/utils/immutable/ does work (the difference being the trailing slash).

If you `curl -i http://alt.js.org/docs/utils/immutable` you get a 301 now. I wonder if we need to define a redirect with jekyll to get this fully working?

**Comment by jdlehman** [comment]
Disregard the above comment. This appears to be working now.
