### ISSUE TITLE
Multiple component instances of one page?

### ISSUE THREAD

**Issue by teeli** [goatslacker/alt#494]
I'm having some trouble wrapping how to use singleton stores when I have multiple instances of a component on the same page. I could use some help in how to do the following in Flux.

More specifically, I have an app built on Alt+React. There's a page that lists multiple categories and the categories have entries as children. All categories have an auto complete text field that allows adding entries to categories. The way it works is that when you write in a text field, it does a search API request (through `EntrySource` as defined in http://alt.js.org/docs/async/) that returns a set of results. The search results are stored in `EntryStore`. The auto complete field listens to changes in `EntryStore` and show a list of matching entries when the user can select an entry to add to a category.

This all works just fine, except when there are multiple categories (and thus multiple auto complete fields) on the same page. In that case, whenever you type in one auto complete field, all of the autocomplete fields get the same results (and shows the result list), because the store is a singleton.

This is pretty much just me failing to "think in Flux", but I just don't get how I could keep the results specific to the fields the search was made in.

**Comment by am80l** [comment]
I'm only just learning Alt as of a few days ago and React as of a few weeks ago, so take this suggestion with a grain of salt - but speaking in general, if your stores are singletons then one option could be to create a new singleton store instance every time you initialize a unique instance of your component - maybe this could be a UID you pass as a jsx attribute that creates the new store on the fly. Using a similar approach it might be possible to create "substores" for your EntryStore, where you still have a single EntryStore but use a UID to reduce the store data specific to your component. Since all members in the store are available in your view, you would essentially just be filtering the data by the UID. 

Hope this helps, would love to hear some other opinions from those more familiar with Alt and React :)

**Comment by goatslacker** [comment]
Oops sorry I thought I replied to this. 

If you have many instances of a component that needs separate instances of alt your only two options are to use all instances or to manage those separate components yourself in your store. 

For example: you store the data in an array and keep track of which index belongs to which component so you can do lookups and writes.

**Comment by teeli** [comment]
Thank you for the help. Per your suggestions I now pass a unique ID from React component whenever making calls and the store saves separate results to separate objects by these IDs. This way my views can filter out all the data that doesn't belong to them, when listening to stores and only act on changes to relevant data. I'm not sure if this is a flux "best practice", but seems to work very well for me at least (this combined with shouldComponentUpdate shouldn't cause much overhead even with many views).

I think my mind is too eager to think stores as collections after years of working like that, when in fact it should be more like stores **contain** collections, I guess.

Anyway. Thanks a lot for the help.

**Comment by goatslacker** [comment]
It's a good practice and you've got it right on what stores are

**Comment by jamesfzhang** [comment]
Any plans to create an abstraction layer inside stores to help manage this exact issue?

**Comment by goatslacker** [comment]
Nope no plans, but feel free to create a userland abstraction
