### ISSUE TITLE
this.dispatch not working with 0.18.0 or 0.18.1

### ISSUE THREAD

**Issue by PedroPinheiro** [goatslacker/alt#564]
With 0.18.0 or 0.18.1, "this.dispatch" is not working into Actions

class LoginActions  {
    login (credentials) {
        this.dispatch(); // this don't have dispatch method
   }
}

I've tested with 0.17.9, everything is doing great...

**Comment by paulallies** [comment]
I've got the same problem

**Comment by jdlehman** [comment]
This is a [breaking change](https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#breaking-changes). Rather than calling `this.dispatch` just return from the function. (you can return a function for async actions)

**Comment by PedroPinheiro** [comment]
TKS!

**Comment by PedroPinheiro** [comment]
MY BAD!

just call with
```javascript
  this.otherAction();
```

**Comment by goatslacker** [comment]
https://github.com/goatslacker/alt/blob/master/CHANGELOG.md#breaking-changes

**Comment by m7moud** [comment]
`this.actions.otherAction();` is still present in the docs, but I'm here because I have a question about `0.18.x` versions.

How can I get an instance of `Flux` in an action, you can find it in `this.alt` in stores, but I can't find it in actions.

**Comment by m7moud** [comment]
I have gone through the commits of `0.18.0`, and I can see that `Store` and `Action` are implemented in two different ways in that version.

`AltAction` class is missing now in favor of the new `ActionsGenerator` class, so I think I will just stick to `0.17.9`.

**Comment by goatslacker** [comment]
Hmm that might be an unintended side effect. Let me have a look

**Comment by goatslacker** [comment]
Nope that was intended. Why not pass in alt yourself?

**Comment by m7moud** [comment]
If so, then this should be listed in the breaking changes, I guess.

In `0.17.x` versions, You can bind an object to an attribute of the Flux instance, for example something like: `this.apiclient = ...`, and this you can just use this as `this.alt.apiclient` in any store or action, and it's mostly needed in actions.

but with `0.18.x` versions, `this.alt` is missing in actions because now the actions is now just a method in an instance of `ActionsGenerator` (it used to be an instance of `AltAction`), but you can still access it in the stores because it's still an instance of `AltStore`, which is really unexpected.

**Comment by m7moud** [comment]
Every Store in `0.17.x` was extended from `AltStore`, and every actions was extended from `AltAction`, but it's the other way around now in `0.18.x` for the actions since it's now implemented as `new ActionsGenerator(UserActions)` and `ActionsGenerator` will just apply the implantation of `UserActions`

**Comment by goatslacker** [comment]
Yup you're right, should be mentioned in breaking changes.

**Comment by goatslacker** [comment]
One way to fix this would be to make `ActionsGenerator.prototype.alt = this` but then you'd also have to have `exportObj.alt = this` and that could be weird because exportObj can be passed in by the user and I wouldn't want to be overriding the keys on that. The thing is that this is still not actually classes. I'm wrapping the method names so I can auto dispatch with the name inferred.

**Comment by m7moud** [comment]
I have thought of this too, but as you said it's a hack job, so I haven't tried to contribute with that, and just kept my project dependent on to `0.17.9`

**Comment by goatslacker** [comment]
:+1: a safe move. I'll keep thinking of ways to keep this behavior.
