### ISSUE TITLE
connectToStores vs other strategies

### ISSUE THREAD

**Issue by Ganasist** [goatslacker/alt#567]
What are the pros and cons of these two View styles:

Style A:
```
class PropertiesView extends React.Component {
  constructor(props) {
    super(props);

    this.onChange = this.onChange.bind(this)
    this.state = PropertiesStore.getState();
  }

  componentDidMount() {
    PropertiesStore.listen(this.onChange);

    PropertiesActions.getList();
  }

  componentWillUnmount() {
    PropertiesStore.unlisten(this.onChange);
  }

  onChange(state) {
    this.setState(state);
  }
```

Style B:
```
@connectToStores
export default class Greeting extends React.Component {
  constructor(props) {
    super(props)
    CustomerActions.fetchCustomers()
  }

  static getStores() {
    return [CustomerStore]
  }
  
  static getPropsFromStores() {
    return CustomerStore.getState()
  }
```

I can get both styles to work, but I prefer Style B and using props in my components. Is there anything Style A vs Style B that I should be aware of before proceeding?

**Comment by jdlehman** [comment]
Both accomplish the same thing as you noted, but there are some slight differences.

Style A creates a component `<PropertiesView />` that has your store data in the state.

Style B creates a tree that looks like: 
```js
<Connect(Greeting)>
  <Greeting {...storeProps} />
</Connect(Greeting)>
```

so essentially Style B creates a wrapper component (`Connect(Greeting)`) for you. This component gets the store data in its state exactly like Style A. The difference is that the store state is passed down to `Greeting` as props, new props being passed down every time the store data changes, meaning `Greeting` will be rerendered.

I recommend using the [React Developer Tools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) to explore the React tree and see the state and props.

So they effectively do the same thing, but using Style B enables you to reuse the component outside of your Flux context (let's say another app) or test the component by just passing props.

If modify Style B as follows

```js
export default class Greeting extends React.Component {
...
}

export const WrappedGreeting = connectToStores(Greeting)
```

we now have 2 things we can import.  The default import being a React component that is powered solely by props. Since this does not rely on the store for its data, we can reuse it in other applications. We can even test it by just passing the props to `Greeting` manually rather than mocking the store object.  We also have a named export, `WrappedGreeting`, that we can use when we want these props to be filled by the store for us rather than doing it manually.
